### ISSUE TITLE
希望加一个国际化

### ISSUE THREAD

**Issue by enjoy-myLife** [zjutjh/WeJH-Taro#165]
用了很多的办法集成多语言都失败了，过来寻大佬

**Comment by j10ccc** [comment]
是在微精弘里面做国际化？我们产品没这个计划。如果你单说技术方案的话，小程序端只能内嵌字典到主包内，vue 的响应式靠直接实现就行了

**Comment by j10ccc** [comment]
你是说你这个 issue 是吧？https://github.com/Moonlightwsn/taro-vue-i18n-lite/issues/1，去你 issue 下聊，别在这个仓库里面聊
