### ISSUE TITLE
首页的成绩查询卡片

### ISSUE THREAD

**Issue by Tianci-King** [zjutjh/WeJH-Taro#8]
2022/12/25🎄star by **Tianci**

## subtask

​		1.点击**绿色小问号**处，显示**帮助卡片弹窗**		

```
若信息长时间无法更新或总是刷新失败，可能是因为更改过正方教务系统的密码，请前往我的-绑定-重新绑定正方账号。
成绩查询中的信息全部来自正方教务系统，数据录入可能会有延迟，请耐心等待。如有疑问请联系教务处，本程序仅作信息展示。
```

​		2.卡片**正文**

​				①下方直接显示**今日已出成绩的科目卡片**（包含**科目名称**，**期中/期末**，**更新时间**的信息）。

​						=>     点击其中的卡片，按其期中/期末的分类进入相应**期中/期末成绩查询**页面

​				②若今日**无新出成绩**，显示为“**今日没有新出的成绩哦~**”

**Comment by Tianci-King** [comment]
已完成1和2.②

**Comment by Tianci-King** [comment]
1.11
完成，提交pr

**Comment by j10ccc** [comment]
- [x] 卡片主体样式
- [x] 帮助弹窗
- [x] 更新时间
- [x] 成绩展示排序
- [x] 点击跳转逻辑

**Comment by j10ccc** [comment]
## TODO
> 需求存在疑点
1. 成绩出分时间判定
2. 期中期末判定
