### ISSUE TITLE
首页的考试安排卡片

### ISSUE THREAD

**Issue by Patrickill** [zjutjh/WeJH-Taro#9]
# 考试安排卡片
需求：
1. 显示最近两天所有场考试的信息（地点，座位，科目，距开考还要多少时间/正在考试）
2. 当日考试结束后该考试安排卡片本日内不消失，卡片顺序依然不变。
3. 点击进入考试安排查询功能界面
4. 点击绿色问号，显示帮助卡片弹窗

**Comment by j10ccc** [comment]
- [ ] 代码注释
- [ ] helpText 文案修改
